export { default as IntroPage } from './introPage/IntroPage'
export { default as ExhibitPage } from './exhibitPage/ExhibitPage'
export { default as ArchivePage } from './archivePage/ArchivePage'
export { default as NewsPage } from './newsPage/NewsPage'
export { default as ErrorPage } from './errorPage/ErrorPage'
